sudo: true
language: scala

matrix:
  allow_failures:
    - scala: 2.13.2

scala:
   - 2.12.11
   - 2.13.2

jdk:
  - openjdk8
  - openjdk12

env: SJS_TEST_BROWSER=chrome

addons:
  chrome: stable

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"

before_script:
  - >
    echo "Getting Chrome Driver: https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip"
  - wget "https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip"
  - mkdir -p chromedriver && unzip chromedriver_linux64.zip -d chromedriver/
  - export PATH="$PATH:$PWD/chromedriver/"

script:
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    coreJS/test
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    clean
    coverage
    core/test

after_success: "sbt core/coverageReport core/coveralls"
