addSbtPlugin("com.timushev.sbt"  % "sbt-updates"   % "0.3.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scoverage"     % "sbt-coveralls" % "1.2.2")
addSbtPlugin("org.foundweekends" % "sbt-bintray"   % "0.5.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.6")
